In [1]:
import pandas as pd # Data analysis and manipultion tool
import numpy as np # Fundamental package for linear algebra and multidimensional arrays
import tensorflow as tf # Deep Learning Tool
import os # OS module in Python provides a way of using operating system dependent functionality
import cv2 # Library for image processing
from sklearn.model_selection import train_test_split # For splitting the data into train and validation set
from sklearn.metrics import f1_score

C:\Users\shahe\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\shahe\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\shahe\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\shahe\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
data=[]
img_size=100 # Here we are taking image size as 100, but it's on you. You can take 50 or 40 or 32 and so on
def create_data():
    for item in ['Negative','Positive']:
        path='C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DPHI Image Pred Cracks/train/'+item+"/"

        for img in os.listdir(path): # os.listdir gets you all the list of name of files located in the given path
            try:
                img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE) # converts the image to pixels and gray scales the images
                new_img_array=cv2.resize(img_array,(img_size,img_size)) # resizing the images
                if item == 'Negative':
                    data.append([new_img_array,0])
                else:
                    data.append([new_img_array, 1]) # appending the list of image pixels and respective target value (i.e. animal type) in data
            except Exception as e:
                    pass # try and except is exception handling case in python, saves you from getting errors


create_data()

KeyboardInterrupt: 

In [4]:
np.random.shuffle(data)
x = []
y = []
for image in data:
    x.append(image[0])
    y.append(image[1])

# converting x & y to numpy array as they are list
x = np.array(x)
y = np.array(y)

In [12]:
X_train, X_val, y_train, y_val = train_test_split(x,y,test_size=0.1)

In [19]:
model = tf.keras.Sequential([
tf.keras.layers.Flatten(input_shape=(100, 100)), # flattening the image
tf.keras.layers.Dense(100, activation='relu'),
tf.keras.layers.Dense(100, activation='relu'),  
tf.keras.layers.Dense(50, activation='relu'),
tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adamax',
loss='binary_crossentropy',
metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=75)

Epoch 1/100
25846/25846 [==============================] - 4s 171us/sample - loss: 27.1518 - acc: 0.5650
Epoch 2/100
25846/25846 [==============================] - 4s 168us/sample - loss: 4.1682 - acc: 0.7026
Epoch 3/100
25846/25846 [==============================] - 4s 170us/sample - loss: 3.0589 - acc: 0.7126
Epoch 4/100
25846/25846 [==============================] - 4s 165us/sample - loss: 3.4140 - acc: 0.7038
Epoch 5/100
25846/25846 [==============================] - 4s 164us/sample - loss: 1.9198 - acc: 0.7540
Epoch 6/100
25846/25846 [==============================] - 4s 165us/sample - loss: 1.2043 - acc: 0.7576
Epoch 7/100
25846/25846 [==============================] - 4s 171us/sample - loss: 0.5508 - acc: 0.8266
Epoch 8/100
25846/25846 [==============================] - 4s 164us/sample - loss: 0.8618 - acc: 0.8009
Epoch 9/100
25846/25846 [==============================] - 4s 165us/sample - loss: 0.6533 - acc: 0.8106
Epoch 10/100
25846/25846 [==============================] - 4s 

In [20]:
model.evaluate(X_val, y_val)

2872/2872 [==============================] - 0s 174us/sample - loss: 0.4200 - acc: 0.8269


[0.4200075967730254, 0.82694983]

In [44]:
test_image_order = pd.read_csv(r"C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DPHI Image Pred Cracks/Testing_set_concrete_crack.csv")
test_image_order.head()

filename
0  Image_1.jpg
1  Image_2.jpg
2  Image_3.jpg
3  Image_4.jpg
4  Image_5.jpg

In [52]:
file_paths = [[fname, r"C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DPHI Image Pred Cracks/test/" + fname] for fname in test_image_order['filename']]

In [53]:
if len(test_image_order) == len(file_paths):
    print('Number of image names i.e. ', len(test_image_order), 'matches the number of file paths i.e. ', len(file_paths))
else:
    print('Number of image names does not match the number of filepaths')

Number of image names i.e.  11282 matches the number of file paths i.e.  11282


In [54]:
test_images = pd.DataFrame(file_paths, columns=['filename', 'filepaths'])
test_images.head()

filename                                          filepaths
0  Image_1.jpg  C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DP...
1  Image_2.jpg  C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DP...
2  Image_3.jpg  C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DP...
3  Image_4.jpg  C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DP...
4  Image_5.jpg  C:/Users/shahe/AI PROJECTS/IMAGE PROCESSING/DP...

In [ ]:
test_pixel_data = [] # initialize an empty numpy array
image_size = 100 # image size taken is 100 here. one can take other size too
for i in range(len(test_images)):
    img_array = cv2.imread(test_images['filepaths'][i], cv2.IMREAD_GRAYSCALE) # converting the image to gray scale
    new_img_array = cv2.resize(img_array, (image_size, image_size)) # resizing the image array
    test_pixel_data.append(new_img_array)
test_pixel_data = np.array(test_pixel_data)

[[203 206 208 ... 202 202 202]
 [204 206 208 ... 203 203 203]
 [205 207 208 ... 205 205 205]
 ...
 [208 208 209 ... 200 202 203]
 [208 208 209 ... 205 207 209]
 [208 208 209 ... 208 210 212]]
[[181 185 185 ... 210 210 210]
 [183 187 188 ... 211 211 211]
 [184 188 191 ... 207 207 207]
 ...
 [187 184 181 ... 177 186 192]
 [187 184 181 ... 180 188 194]
 [187 184 181 ... 182 191 197]]
[[154 158 163 ... 159 156 153]
 [153 157 162 ... 162 159 157]
 [153 157 161 ... 164 161 159]
 ...
 [150 151 153 ... 151 154 157]
 [150 152 153 ... 153 156 159]
 [150 152 153 ... 155 158 161]]
[[152 148 145 ... 145 145 145]
 [150 148 146 ... 142 142 142]
 [148 147 147 ... 146 146 146]
 ...
 [150 153 154 ... 140 141 142]
 [150 153 154 ... 140 141 142]
 [150 153 154 ... 142 143 144]]
[[186 189 192 ... 191 191 191]
 [187 190 193 ... 190 190 190]
 [189 192 195 ... 190 190 190]
 ...
 [223 220 215 ... 183 183 183]
 [210 208 204 ... 185 185 185]
 [200 198 196 ... 188 188 188]]
[[188 189 190 ... 176 178 180]
 [190 190

In [39]:
pred = model.predict(test_pixel_data)

ValueError: When using data tensors as input to a model, you should specify the `steps` argument.

In [20]:
prediction = []
for value in pred:
    if value < 0.5:
        prediction.append("Negative")
    else:
        prediction.append("Positive")

In [22]:
res = pd.DataFrame({'prediction': prediction}) # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("ConcreteSub.csv", index = False) # the csv file will be saved locally on the same location where this notebook is located.